# Generated by Django 5.2.1 on 2025-05-26 03:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('comments', models.TextField()),
                ('sentiment_results', models.TextField()),
                ('word_frequency', models.TextField()),
                ('csv_file', models.FileField(upload_to='csv/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
