# Generated by Django 5.2.1 on 2025-05-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTiktok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pie_chart', models.ImageField(blank=True, null=True, upload_to='charts/pie/')),
                ('bar_chart', models.ImageField(blank=True, null=True, upload_to='charts/bar/')),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='ApiTiktok.dokument')),
            ],
        ),
    ]
